# Generated by Django 4.2.8 on 2024-01-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Address', models.TextField(max_length=500)),
                ('Account_type', models.CharField(max_length=50)),
                ('Materials', models.CharField(max_length=500)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingApp.branches')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingApp.districts')),
            ],
        ),
        migrations.AddField(
            model_name='branches',
            name='selectdistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingApp.districts'),
        ),
    ]
